version: '3.9'
services:
  db:
    image: postgres:latest
    volumes:
      - ./data:/var/lib/postgresql/data
    container_name: db
    ports:
      - 5432:5432
    restart: 'always'
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "db", "-U", "postgres"]
      timeout: 10s
      retries: 10
    cap_add:
      - SYS_NICE
